// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xscurve_adder36.h"

extern XScurve_adder36_Config XScurve_adder36_ConfigTable[];

XScurve_adder36_Config *XScurve_adder36_LookupConfig(u16 DeviceId) {
	XScurve_adder36_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSCURVE_ADDER36_NUM_INSTANCES; Index++) {
		if (XScurve_adder36_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XScurve_adder36_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XScurve_adder36_Initialize(XScurve_adder36 *InstancePtr, u16 DeviceId) {
	XScurve_adder36_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XScurve_adder36_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XScurve_adder36_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

