// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xscurve_adder36.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XScurve_adder36_CfgInitialize(XScurve_adder36 *InstancePtr, XScurve_adder36_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XScurve_adder36_Start(XScurve_adder36 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_AP_CTRL) & 0x80;
    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XScurve_adder36_IsDone(XScurve_adder36 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XScurve_adder36_IsIdle(XScurve_adder36 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XScurve_adder36_IsReady(XScurve_adder36 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XScurve_adder36_EnableAutoRestart(XScurve_adder36 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_AP_CTRL, 0x80);
}

void XScurve_adder36_DisableAutoRestart(XScurve_adder36 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_AP_CTRL, 0);
}

void XScurve_adder36_Set_N_ADDS(XScurve_adder36 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_N_ADDS_DATA, Data);
}

u32 XScurve_adder36_Get_N_ADDS(XScurve_adder36 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_N_ADDS_DATA);
    return Data;
}

void XScurve_adder36_InterruptGlobalEnable(XScurve_adder36 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_GIE, 1);
}

void XScurve_adder36_InterruptGlobalDisable(XScurve_adder36 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_GIE, 0);
}

void XScurve_adder36_InterruptEnable(XScurve_adder36 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_IER);
    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_IER, Register | Mask);
}

void XScurve_adder36_InterruptDisable(XScurve_adder36 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_IER);
    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_IER, Register & (~Mask));
}

void XScurve_adder36_InterruptClear(XScurve_adder36 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScurve_adder36_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_ISR, Mask);
}

u32 XScurve_adder36_InterruptGetEnabled(XScurve_adder36 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_IER);
}

u32 XScurve_adder36_InterruptGetStatus(XScurve_adder36 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XScurve_adder36_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XSCURVE_ADDER36_CTRL_BUS_ADDR_ISR);
}

